[profile.default]
src = "."
test = "test"
script = "script"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = ["forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
